#!/usr/bin/env npx ts-node
// audit-permissions.ts: Scan for --dangerously-skip-permissions usage and generate registry.

import fs from 'node:fs';
import path from 'node:path';

const ROOT: string = path.resolve(__dirname, '..');
const OUTPUT: string = path.join(ROOT, 'references', 'registries', 'permission-bypass-registry.md');

const SCAN_DIRS: string[] = ['web', 'scripts', '.claude'];
const SKIP_DIRS: Set<string> = new Set(['node_modules', '.git']);
const PATTERNS: string[] = [
  'dangerously-skip-permissions',
  'dangerouslySkipPermissions',
  'DangerouslySkipPermissions',
  'dangerouslyDisableSandbox',
  'bypassPermissions'
];

interface Finding {
  file: string;
  line: number;
  content: string;
  pattern: string | undefined;
  guardrails: string;
}

function matchesPattern(line: string): boolean {
  return PATTERNS.some(p => line.includes(p));
}

function detectGuardrails(lines: string[], lineNum: number): string {
  // lineNum is 0-based index into lines array
  const start: number = Math.max(0, lineNum - 3);
  const end: number = Math.min(lines.length, lineNum + 4);
  const context: string = lines.slice(start, end).join(' ');
  const guardrails: string[] = [];

  if (context.includes('allowedTools') || context.includes('--allowedTools')) {
    const match: RegExpMatchArray | null = context.match(/allowedTools[^'"\s]*[,\s]+['"]?([A-Za-z,]+)/);
    if (match) {
      guardrails.push('allowedTools: ' + match[1]);
    } else {
      guardrails.push('allowedTools present');
    }
  }
  if (context.includes('--model') || context.includes("'--model'") || context.includes('"--model"')) {
    guardrails.push('model specified');
  }
  if (context.includes('VALID_MODELS') || context.includes('validModels')) {
    guardrails.push('model validation');
  }

  return guardrails.length > 0 ? guardrails.join('; ') : 'none detected';
}

function scanFile(filePath: string): Finding[] {
  let content: string;
  try {
    content = fs.readFileSync(filePath, 'utf8');
  } catch {
    return [];
  }

  const lines: string[] = content.split('\n');
  const results: Finding[] = [];
  const rootRelative: string = path.relative(ROOT, filePath);

  lines.forEach((line: string, idx: number) => {
    if (matchesPattern(line)) {
      const pattern: string | undefined = PATTERNS.find(p => line.includes(p));
      results.push({
        file: rootRelative,
        line: idx + 1,
        content: line.trim(),
        pattern,
        guardrails: detectGuardrails(lines, idx)
      });
    }
  });

  return results;
}

function scanDir(dirPath: string): Finding[] {
  const results: Finding[] = [];

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true });
  } catch {
    return results;
  }

  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;

    const fullPath: string = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      results.push(...scanDir(fullPath));
    } else if (entry.isFile()) {
      // Only scan text-like files
      const ext: string = path.extname(entry.name);
      const textExts: Set<string> = new Set(['.js', '.ts', '.json', '.md', '.sh', '.yaml', '.yml', '.txt', '']);
      if (textExts.has(ext)) {
        results.push(...scanFile(fullPath));
      }
    }
  }

  return results;
}

function escapeCell(str: string): string {
  // Escape pipe characters for markdown table cells
  return str.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function generateRegistry(findings: Finding[]): string {
  const lines: string[] = [
    '# Permission Bypass Registry',
    '',
    'Auto-generated by `npm run audit:permissions`. Do not edit manually.',
    '',
    'This registry documents every location in the codebase where a permission bypass flag',
    '(`--dangerously-skip-permissions`, `dangerouslySkipPermissions`, `dangerouslyDisableSandbox`)',
    'is used, along with any detected guardrails that limit the scope of the bypass.',
    '',
    '| File | Line | Pattern | Context | Guardrails |',
    '| --- | --- | --- | --- | --- |'
  ];

  if (findings.length === 0) {
    lines.push('| (none found) | | | | |');
  } else {
    for (const f of findings) {
      lines.push(
        `| ${escapeCell(f.file)} | ${f.line} | \`${f.pattern}\` | \`${escapeCell(f.content)}\` | ${escapeCell(f.guardrails)} |`
      );
    }
  }

  lines.push('');
  lines.push(`_Last updated: ${new Date().toISOString()}_`);
  lines.push('');

  return lines.join('\n');
}

function main(): void {
  const allFindings: Finding[] = [];

  for (const dir of SCAN_DIRS) {
    const fullDir: string = path.join(ROOT, dir);
    if (fs.existsSync(fullDir)) {
      allFindings.push(...scanDir(fullDir));
    }
  }

  const markdown: string = generateRegistry(allFindings);
  fs.writeFileSync(OUTPUT, markdown, 'utf8');

  const count: number = allFindings.length;
  process.stdout.write(`audit-permissions: found ${count} occurrence${count !== 1 ? 's' : ''}, wrote ${path.relative(ROOT, OUTPUT)}\n`);
}

main();
