'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { execSync } = require('node:child_process');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');

function grepCount(needle: string, ext: string): number {
  try {
    const out = execSync(
      `git ls-files -- '*.${ext}' | xargs grep -l ${JSON.stringify(needle)} 2>/dev/null || true`,
      { cwd: ROOT, encoding: 'utf8' }
    );
    const files = out
      .split('\n')
      .map((s: string) => s.trim())
      .filter((s: string) => s.length > 0)
      // Exclude the two workflow-consolidation tests themselves, which reference the
      // deleted filenames as forbidden strings.
      .filter((s: string) => !s.endsWith('web/test/workflow-references.test.ts'))
      .filter((s: string) => !s.endsWith('web/test/core-workflow-doc.test.ts'))
      // Exclude the path-registry CSV, which is regenerated by scripts/extract_paths.py.
      // Once no markdown still references the deleted files, the CSV rows will disappear on regeneration.
      .filter((s: string) => !s.endsWith('references/registries/path-registry.csv'));
    return files.length;
  } catch {
    return 0;
  }
}

describe('workflow-references sweep', () => {
  it('no inbound refs to contributing.md remain in *.md', () => {
    assert.equal(grepCount('contributing.md', 'md'), 0, 'contributing.md still referenced in markdown');
  });

  it('no inbound refs to commit-procedure.md remain in *.md', () => {
    assert.equal(grepCount('commit-procedure.md', 'md'), 0, 'commit-procedure.md still referenced in markdown');
  });

  it('no inbound refs to contributing.md remain in *.json', () => {
    assert.equal(grepCount('contributing.md', 'json'), 0);
  });

  it('no inbound refs to commit-procedure.md remain in *.json', () => {
    assert.equal(grepCount('commit-procedure.md', 'json'), 0);
  });

  it('no inbound refs to contributing.md remain in *.ts', () => {
    assert.equal(grepCount('contributing.md', 'ts'), 0);
  });

  it('no inbound refs to commit-procedure.md remain in *.ts', () => {
    assert.equal(grepCount('commit-procedure.md', 'ts'), 0);
  });
});
